### PR TITLE
Afegim la xerrada de "No tot és pogramar!"

### PR DESCRIPTION
**Pull request by ecarreras**
Afegim el repositori de la xerrada [No tot és programar!](https://ecarreras.github.io/xerrada-pygrn-no-tot-es-programar/#1)

### CODE REVIEW

**Review by XaviTorello — CHANGES_REQUESTED** [review]
Great, many thanks 🍫 

Would be great if also you can modify the main REAME 😃

**Comment by ecarreras** [comment]
Sure!

**Comment by ecarreras** [comment]
> Would be great if also you can modify the main REAME

What I've to modify from README file? I see that the other talks aren't added to the README

**Comment by XaviTorello** [comment]
The main README file list the already done / planified sessions, and point to the related "sub" README file (or the meetup for future sessions).

Right now the main README list:
```
Xerrades realitzades i planificació de les properes

- 12/07/2017 - PyGRN#1 -> xerrades/20170712/README.md
- 13/09/2017 - PyGRN#2 -> meetup.com/....
```

The second session, "13/09/2017 - PyGRN#2" still links to the related meetup page, instead linking to your ppt.

Maybe could be interesting to:
1) Create 20170913/README.md to introduce this second session as it's done with the first one (see [this](https://github.com/pygrn/xerrades/blob/master/xerrades/20170712/README.md))
2) Modify main README.md to link to 1) instead of the meetup page

With this we will ensure a better user experience.

What do you think about it?

**Comment by ecarreras** [comment]
> What do you think about it?

Done!

**Review by XaviTorello — APPROVED** [review]
Perfect! Many thanks :poultry_leg:

**Pull request merged**
